[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3
solc = '0.8.22'
optimizer = true
optimizer_runs = 20_000
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
  'solidity-bytes-utils/=lib/solidity-bytes-utils/contracts/'
]

[fuzz]
runs = 10

# https://book.getfoundry.sh/reference/config/formatter
[fmt]
bracket_spacing = true

[profile.ci.fuzz]
runs = 10
seed = '0xffff'