name: CI
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - foundry.toml
      - .github/workflows/*.yml
  pull_request:
    paths:
      - src/**
      - test/**
      - foundry.toml
      - .github/workflows/*.yml

env:
  FOUNDRY_PROFILE: ci

jobs:
  forge-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test
